services:
  postgres:
    image: postgres:17-alpine
    container_name: kitnebheju-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kitnebheju

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: kitnebheju-app

    env_file:
      - .env.docker

    ports:
      - "3000:3000"

    depends_on:
      - postgres
volumes:
  postgres_data:
